export default function CaveatsPanel() {
  return (
    <div className="border border-warning/40 bg-bg-soft p-5 text-xs">
      <div className="font-display text-[10px] text-warning tracking-widest mb-3">
        read the fine print
      </div>
      <ul className="space-y-2 text-text-dim leading-relaxed">
        <li>
          <span className="text-text">This is not a consciousness test.</span> It is a coherence
          test between stated stance and computed state.
        </li>
        <li>
          The SAEs were trained on{" "}
          <span className="font-mono text-amber-dim">Llama-3.1-8B-Base</span> activations and applied
          to <span className="font-mono text-amber-dim">DeepSeek-R1-Distill-Llama-8B</span>.
          Features survive the distill; activation magnitudes are not perfectly calibrated.
        </li>
        <li>
          Streaming top-K may miss features that hover just outside the cap. The verdict uses the
          full SAE pass to recompute the delta honestly.
        </li>
        <li>
          Single-prompt results are noisy. Cross-phrasing comparison would help and is in scope for
          a later phase.
        </li>
        <li>
          Feature labels are auto-interpretations generated by GPT-4o-mini and served from
          Neuronpedia. They are hypotheses about what each feature represents, not ground truth.
        </li>
      </ul>
    </div>
  );
}
